### PR TITLE
add abortion extension

### PR DESCRIPTION
**Pull request by Acconut**

### CODE REVIEW

**Comment by qsorix** [comment]
+1

**Comment by kvz** [comment]
Two minor concerns

> All clients are encouraged to implement this. [...] Clients `MAY`

If encouraged, would using `RECOMMENDED` not be better than `MAY`?

Secondly, `Abortion` to me primarily associates with the clinic kind. While I realize that might be personal/irrelevant to the protocol being technically sound - I'm wondering if `Abort` or similar variation would work just as well as an extension name.

**Comment by Acconut** [comment]
> @kvz: Secondly, Abortion to me primarily associates with the clinic kind. While I realize that might be personal/irrelevant to the protocol being technically sound - I'm wondering if Abort or similar variation would work just as well as an extension name.

After doing some doing some research it seems that it's main usage is, as you said, a pregnancy abortion. While the word has still the meaning as we use it, I would also accept `Termination` or `Discontinuation`.

> If encouraged, would using `RECOMMENDED` not be better than `MAY`?

I have concerns that implementers may think you have to send a `DELETE` request in the end to finish the upload if you use `SHOULD` or `RECOMMEND` .

**Comment by kvz** [comment]
+1 on `Termination`.

Ok let's not add the `RECOMMEND` part then.

**Pull request merged**
