### PR TITLE
Add collaborators

### PR DESCRIPTION
**Pull request by Acconut**
In order to thanks all the current collaborators who contributed their ideas and opinions and therefore helped to form the final (and soon coming) 1.0 release of tus, we would like to mention every one of you in the specification. The order in which the names appear does not have any meaning, we just got it this way from GitHub :).

If you do not want to appear on this list or want to change your name either leave a comment on this issue or drop me an e-mail (marius@transloadit.com) and I will get it sorted as soon as possible.

The plan is to merge this pull request shortly before the pull request for the 1.0 update (#57) which will be in a week or so.

Finally, I want to thank all of you again for helping tus to become what it is now. :+1: 

@hintjens @khangtoh @jerefrer @Amodio @srijs @brunodecarvalho @cybic @sandfox @aranw @Baughn @j4james @noptic @schmerg @ehd @homeworkprod @andrewfenn @evert @reschke @kevinswiber @radiospiel @0x20h @qsorix @kless @luk- @tino @ChristianUlbrich @sheeep @jonhoo @wronglink @technoweenie @MarkMurphy @jf @pmdarrow @Gargaj @timemachine3030

### CODE REVIEW

**Comment by biasedbit** [comment]
Damn, totally missed this. I've since changed the handle from @brunodecarvalho to @biasedbit. Sorry :(

**Comment by MarkMurphy** [comment]
:+1: thanks, appreciate this!

**Comment by kvz** [comment]
@biasedbit I'll change it : )

**Comment by kvz** [comment]
I guess now that I have all the collaborators together, it makes sense to share in case you missed it or this wasn't clear: Today we *finally* launched 1.0.

Blog post: http://tus.io/blog/2015/11/16/tus.1.0/
Some initial press coverage: http://tech.eu/features/6672/transloadit-tus-protocol-vimeo/
Reddit thread: https://www.reddit.com/r/programming/comments/3t0rb2/berlinbased_transloadit_wants_to_fix_broken_file/
HN: https://news.ycombinator.com/item?id=10574364

Ok, back to celebrating :smile: :cocktail: :tada:

**Comment by radiospiel** [comment]
Just found about this. Thanks for mentioning me here, and good luck!

**Comment by Acconut** [comment]
@radiospiel Thank you for being part of it :)

**Pull request merged**
